# Generated by Django 4.1.3 on 2022-12-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_bookroom_date'),
        ('admindash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='dashboard.bookroom')),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
                'ordering': ('id',),
            },
        ),
    ]
