# Generated by Django 4.1.3 on 2022-12-04 10:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0002_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(unique=True)),
                ('date', models.DateField(default=datetime.date(2022, 12, 4))),
                ('fullname', models.CharField(max_length=255)),
                ('room_id', models.IntegerField()),
                ('no_of_beds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('floor_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('select_bed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'BookRoom',
                'verbose_name_plural': 'BookRooms',
                'ordering': ('book_id',),
            },
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
