# Generated by Django 4.1.3 on 2022-11-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('date', models.DateField()),
                ('fullname', models.CharField(max_length=255)),
                ('room_id', models.IntegerField()),
                ('no_of_beds', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('select_bed', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BookRoom',
                'verbose_name_plural': 'BookRooms',
                'ordering': ('book_id',),
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('room_id',), 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
    ]
