# Generated by Django 4.1.3 on 2022-11-19 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_bookroom_alter_room_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='book_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='floor_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='no_of_beds',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='select_bed',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
