# Generated by Django 4.1.3 on 2022-11-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_sample_alter_bookroom_book_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
