# Generated by Django 4.1.3 on 2022-12-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_register'),
        ('dashboard', '0005_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='useraccounts.login'),
        ),
    ]
