# Generated by Django 4.1.3 on 2022-12-03 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_bookroom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 3)),
        ),
    ]
